/// <reference types="vite/client" />
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */


export const projectId = import.meta.env.VITE_SUPABASE_URL ? import.meta.env.VITE_SUPABASE_URL.split('//')[1]?.split('.')[0] : 'unknown';
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
